name: Setup KinD Cluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Install KinD (Kubernetes in Docker)
      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 3: Install kubectl (Kubernetes CLI)
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Step 4: Create KinD cluster named "burlyaev-cluster"
      - name: Create KinD cluster
        run: |
          kind create cluster --name burlyaev-cluster --wait 5m

      # Step 5: Set KUBECONFIG environment variable properly
      - name: Set KUBECONFIG environment variable
        run: |
          export KUBECONFIG="$(kind get kubeconfig --name burlyaev-cluster)"
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV

      # Step 6: Verify kubectl connection to the KinD cluster
      - name: Get cluster info
        run: kubectl cluster-info
